# Generated by Django 4.2.10 on 2024-02-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourcategory',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
    ]
